### PR TITLE
Allow communication request and/or response tracing

### PR DESCRIPTION
**Pull request by oldpec**
An interface SDK clients can implement to capture comms requests/responses.
Changes to config and container to optionally carry such classes through to communications class.

### CODE REVIEW

**Comment by craigcarnell** [comment]
Please look at merging this!

**Comment by markhagan** [comment]
> Please look at merging this!

We are having a look. Thanks!

**Comment by daveodwyer** [comment]
+1 on this

Any chance this could be merged?

**Comment by CristinaNechitaGP** [comment]
you can capture raw request/response by setting the "requestLogger" on the config object. Example: https://github.com/globalpayments/php-sdk/blob/master/test/Data/BaseGpApiTestConfig.php#L47

**Pull request closed without merging**
